config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers
  root to: "home#index"
  resources :home
  resources :orders
  resources :line_items, only: [:update]
  get "add_to_cart" => "orders#add_to_cart"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name,  presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name,  presence: true
  validates :email,  presence: true
  validates :funds, numericality: { only_float: true, greater_than_or_equal_to: 0 }
  has_many :line_items

  has_many :orders,-> { distinct }, through: :line_items
end

app/models/discount.rb
class Discount < ApplicationRecord
  has_many :orders
  validates :product_ids,  presence: true, length: {
    minimum: 2,
    message: 'Minimum 2 products are required'
  }
  validates :value, presence: true, numericality: { 
    only_float: true,
    greater_than: 0,
    less_than: 100
  }

  before_validation :product_compact

  private
  
  def product_compact
    self.product_ids&.compact!
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :customer
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
  validates :tax, numericality: { only_float: true, greater_than_or_equal_to: 0 }
  validates :total, numericality: { only_float: true, greater_than_or_equal_to: 0 }

  before_save :calculate_total

  def calculate_total
    product = self.product
    if product.free
      self.total = 0
      self.tax = 0
    elsif product.vat.zero?
      self.total = product.price.to_f * self.quantity.to_f
      self.tax = 0
    else
      tax_value = (product.price.to_f * product.vat.to_f)/ 100
      self.tax = self.quantity.to_f * tax_value
      self.total = (self.quantity.to_f * product.price.to_f) + self.tax.to_f
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { cart: 0, paid: 1, completed: 2 }
  has_many :line_items, dependent: :destroy
  has_many :customers, through: :line_items
  has_many :products, through: :line_items
  belongs_to :discount, optional: true
  validates :discount_value, numericality: { only_float: true, greater_than_or_equal_to: 0 }
  validates :total, numericality: { only_float: true, greater_than_or_equal_to: 0 }

  def modify
    self.total = self.line_items.sum("CAST(COALESCE(total, '0') AS DECIMAL)").to_s
    discount = Discount.where("product_ids <@ ARRAY[?]", self.product_ids)&.first
    if discount.present?
      self.discount = discount
      self.discount_value = ((self.total.to_f * discount.value.to_f)/100)
      order_total = self.total.to_f - self.discount_value.to_f
      self.total = [order_total, 0].max
    end
    self.save
  end

  def placed
    if self.total.to_f <= self.customers.first.funds.to_f
      self.status = "paid"
      funds = self.customers.first.funds.to_f - self.total.to_f
      self.customers.update(funds: funds)
      self.line_items.each do |line_item|
        pro = line_item.product
        quantity = pro.quantity - line_item.quantity
        quantity = [quantity, 0].max
        pro.update(quantity: quantity)
      end
      self.save
    else
      self.errors.add(:base, "order total exceed the customer funds")
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :title,  presence: true
  validates :status,  presence: true
  validates :vat,  presence: true
  validates :quantity,  presence: true
  validates :price,  presence: true
  enum status: { draft: 0, published: 1, unavailable: 2 }
  validates :price, numericality: { only_float: true, greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :vat, numericality: { only_integer: true, greater_than_or_equal_to: 0,  less_than: 100 }
  has_one_attached :image
  has_many :line_items

  def self.active
    where(status: "published")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.active
    @products = @products.where(category_id: params[:category]) if params[:category].present?
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def update
    line_item = LineItem.find(params[:id])
    order = line_item.order
    if line_item.update(line_item_params)
      order.modify
      render json: { data: line_item, order: order }, ststus: :ok
    else
      render json: { error: line_item.errors }, ststus: :unprocessible_entity
    end

  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :find_order, except: [:new, :add_to_cart, :index]

  def index
    @orders = current_customer.orders.where.not(status: "cart")
  end

  def new
    @order = current_customer.orders.find_by(status: "cart")
    @discount_rate = @order.discount&.value
    @line_items = @order.line_items
  end

  def update
    if @order.placed
      redirect_to :root, notice: "Order placed"
    else
      redirect_to :root, errors: @order.errors
    end
  end
  
  def add_to_cart
    product = Product.find_by(id: params[:product_id])
    if product.present?
      create_or_update_order(product.id)
    end
    redirect_to :root
  end

  def destroy
   
   @order.destroy
   redirect_to :root
  end

  private

  def find_order
    @order = Order.find(params[:id])
  end

  def create_or_update_order product_id
    order = current_customer.orders.where(status: "cart").where("line_items.product_id = ?", product_id).first
    unless order.present?
      order = Order.find_or_initialize_by(status: "cart")
      line_item = order.line_items.new
      line_item.product_id = product_id
      line_item.quantity = 1
      line_item.customer = current_customer
      order.save
      order.modify
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def categories
    Category.all
  end

  def cart_count
    current_customer.orders.where(status: "cart").first&.line_items&.count
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3">
        <div class="card" style="width: 18rem;">
         <% if product.image.present? %> 
            <img src="<%= url_for(product.image) %>" class="card-img-top" height="300" alt="...">
         <% else %>
            <img src="https://via.placeholder.com/150" class="card-img-top" alt="...">
         <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.title %></h5>
          <p class="card-text"> <%= product.description %></p>
          <p class="card-text">Full Details: <%= product.detail %></p>
          <% if product.free %>
              <p class="card-text">Free</p>
          <% else %>
            <p class="card-text">Price: <%= product.price %></p>
            <p class="card-text">Tax: <%= product.vat %> %</p>
          <% end %>
          <% if customer_signed_in? %>
          <%= link_to "Add to cart", add_to_cart_path(product_id: product.id), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Status</th>
      <th scope="col">Total</th>
      <th scope="col">Discount</th>
    </tr>
  </thead>
  <tbody>
    <% if @orders.present? %>
    	<% @orders.each do |order| %>
  	  	<tr>
  	      <th scope="row"><%= order.id %></th>
  	      <td><%= order.status %></td>
  	      <td><%= order.total %></td>
  	      <td><%= order.discount_value %></td>
  	    </tr>

    	<% end %>
    <% else %>
      No order placed
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-12 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class=" badge-secondary badge-pill"><%= cart_count%></span>
          </h4>
          <ul class="list-group mb-3 z-depth-1">
            <% @line_items.each do |line_item| %>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0"><%= line_item.product.title %></h6>
                </div>
               <div>
                  <input type="number" class="my-0" placeholder="Quantity" value="<%= line_item.quantity %>" min="1", onchange="update_item(<%= line_item.id %>, this)">
                </div>
                <span class="text-muted  <%= "#{line_item.id}-total total" %>"><%= line_item.total %></span>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div class="text-danger">
                  <h6 class="my-0"><%= line_item.product.title %> TAX</h6>
                  <small>@<%= line_item.product.vat %>%</small>
                </div>
                <span class="text-danger <%= "#{line_item.id}-tax" %>">+ <%= line_item.tax %></span>
              </li>
            <% end %>

            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Discount @ <%= @discount_rate.present? ? @discount_rate : 0 %>%</h6>
              </div>
              <span class="text-success order-discount">-<%= @order.discount_value %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total</span>
              <strong class="order-total"><%= @order.total %> </strong>
            </li>
          </ul>

        </div>
        <!--Grid column-->


      </div>
      <!--Grid row-->
      <% if @order.total.to_f <= current_customer.funds.to_f %>
        <button type="button" class="btn btn-success btn-lg btn-block" onclick="order_placed(<%= @order.id %>)"> Pay Now</button>
      <% end %>
       <%= link_to "Clear cart", order_path(@order), class: "btn btn-success btn-lg btn-block", method: :delete, confirm: "Are you sure?" %>
    </div>

  </main>
  <!--Main layout-->

<script type="text/javascript">
  function update_item(item, obj) {
    var quantity = $(obj).val();
    $.ajax({
      type: "PUT",
      url: "/line_items/" + item,
      data: {"line_item": { "quantity": quantity }}
    }).done(function( data ) {
      $("." + data.data.id + "-total").html(data.data.total);
      $("." + data.data.id + "-tax").html(data.data.tax);
      $(".order-discount").html("-" + data.order.discount_value);
      $(".order-total").html(data.order.total);
    });
  }

  function order_placed(order) {
    $.ajax({
      type: "PUT",
      url: "/orders/" + order
    });
  }
</script>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Cafe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <%= link_to "All", root_path, class: "dropdown-item" %>
            </li>
            <% categories.each do |category| %>
              <li>
                <%= link_to category.name, root_path(category: category.id), class: "dropdown-item" %>
              </li>
            <% end %>  
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/orders">Orders</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if customer_signed_in? %>
              <li>
                <%= link_to "Edit", edit_customer_registration_path, class: "dropdown-item" %>
              </li>
              <li>
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true" data-bs-toggle="tooltip" data-bs-placement="top" title="Tooltip on top">Add Funds</a>
              </li>
              <li>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to "Sign out", destroy_customer_session_path, class: "dropdown-item", method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to "Sign in", new_customer_session_path, class: "dropdown-item" %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
      
       <% if customer_signed_in? %>
       <p class="mr-5">Funds available: <%= current_customer.funds %></p>
          <a href="/orders/new" class="btn btn-success">cart(<%= cart_count %>)</a>
       <% end %>
    </div>
  </div>
</nav>